name: CI
on: [push]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to nerdhood.de
      uses: appleboy/ssh-action@master
      env:
        USERNAME: doleyduy
        HOST: 35.198.220.200
        SCRIPT: mkdir /home/doleduy/TestGit/ok
        KEY: ${{ secrets.SERVER_SSH_KEY }}
